sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zhaomeng123
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tCugWDeqPmnrX59rmYg
    access-key-secret: oNDM2Gv8FJlunQTCs0EUcNczENcPtI
    bucket-name: sky-takeout150101
  redis:
    host: localhost
    port: 6379
    password: zhaomeng123
    database: 0